"""Explicit reliability recommendations and atomic audit persistence, never execution."""
from datetime import datetime, timezone
from uuid import UUID

from qa_sentinel.domain.decision import DecisionRecord
from qa_sentinel.domain.enums import DecisionType, TaskState
from qa_sentinel.domain.event import Event
from qa_sentinel.domain.references import CorrelationRef
from qa_sentinel.persistence.records import FailureFingerprint
from qa_sentinel.persistence.unit_of_work import UnitOfWork
from .reliability_policy import (
    ReliabilityConfig, RetryDomain, FailureDisposition, RecoveryAction, RetryRequest,
    FailureIdentity, InvestigatorContext, BlockerReason, evaluate_retry,
    evaluate_circuit_breaker, evaluate_investigator_escalation, evaluate_blocker,
)


class ReliabilityService:
    def __init__(self, session_factory, config: ReliabilityConfig | None = None):
        self.session_factory = session_factory
        self.config = config or ReliabilityConfig()

    @staticmethod
    def _task(uow, task_id, correlation):
        task = uow.tasks.get(task_id)
        if task is None:
            raise KeyError(task_id)
        if task.state in {TaskState.DONE, TaskState.FAILED}:
            raise ValueError("Terminal tasks cannot schedule recovery")
        # Correlation is evidence, not a way to link arbitrary tasks or decisions.
        for identifier, getter in (
            (correlation.invocation_id, uow.invocations.get),
            (correlation.artifact_id, uow.artifacts.get),
            (correlation.test_run_id, uow.history.get_test_run),
        ):
            if identifier is not None:
                record = getter(identifier)
                if record is None or record.task_id != task_id:
                    raise ValueError("Correlation evidence is missing or belongs to another task")
        if correlation.decision_id is not None:
            raise ValueError("Decision correlation is generated by the service")
        return task

    @staticmethod
    def _record(uow, task_id, decision_type, code, details, refs, correlation,
                event_type=None, payload=None):
        now = datetime.now(timezone.utc)
        entity_refs = tuple(str(identifier) for identifier in (
            correlation.invocation_id, correlation.artifact_id, correlation.test_run_id)
            if identifier is not None)
        decision = DecisionRecord(task_id=task_id, decision_type=decision_type,
            decision_source="ORCHESTRATOR", reason_code=code, reason_details=details,
            evidence_refs=tuple(refs) + entity_refs, created_at=now)
        uow.history.append_decision(decision)
        if event_type is not None:
            event = Event(task_id=task_id, event_type=event_type, timestamp=now,
                actor=dict(type="ORCHESTRATOR", id="qa-sentinel"),
                correlation=CorrelationRef(**{**correlation.model_dump(), "decision_id": decision.id}),
                payload={"reason_code": code, "recommendation_only": True, **(payload or {})})
            uow.history.append_event(event)
        return decision

    def _failure(self, uow, task_id, identity, correlation, escalation_available):
        if correlation.test_run_id is None:
            raise ValueError("Failure fingerprints require test-run evidence")
        digest = identity.fingerprint()
        matches = [f for f in uow.failure_fingerprints.list_by_task(task_id) if f.fingerprint == digest]
        if len(matches) > 1:
            raise ValueError("Ambiguous existing failure fingerprint")
        now = datetime.now(timezone.utc)
        if matches:
            original = matches[0]
            count = original.occurrence_count + 1
            uow.failure_fingerprints.update_occurrence(original.id, count, now)
            fingerprint = uow.failure_fingerprints.get(original.id)
        else:
            count = 1
            fingerprint = FailureFingerprint(task_id=task_id, test_run_id=correlation.test_run_id,
                fingerprint=digest, **identity.model_dump(), occurrence_count=count,
                first_seen_at=now, last_seen_at=now)
            uow.failure_fingerprints.add(fingerprint)
        circuit = evaluate_circuit_breaker(count, escalation_available=escalation_available, config=self.config)
        if circuit.tripped:
            kind = DecisionType.ESCALATE_MODEL if circuit.recommended_action == RecoveryAction.ESCALATE else DecisionType.BLOCK
            self._record(uow, task_id, kind, circuit.reason_code,
                "Repeated normalized failure stops automatic same-path retry.", (str(fingerprint.id),),
                correlation, "CIRCUIT_BREAKER_TRIPPED", circuit.model_dump(mode="json"))
        return fingerprint, circuit

    def record_failure(self, *, task_id: UUID, identity: FailureIdentity,
                       correlation: CorrelationRef, escalation_available: bool = False):
        with UnitOfWork(self.session_factory) as uow:
            task = self._task(uow, task_id, correlation)
            available = self._escalation_available(uow, task, escalation_available)
            result = self._failure(uow, task_id, identity, correlation, available)
            uow.commit()
            return result

    def _escalation_available(self, uow, task, requested):
        # Task 4 permits model escalation only for Investigator, within its durable budget.
        count = sum(e.event_type == "MODEL_ESCALATED" for e in uow.history.list_events(task.id))
        return bool(requested and task.state == TaskState.INVESTIGATING
                    and count < self.config.investigator_escalation_limit)

    def retry(self, *, task_id: UUID, domain: RetryDomain, disposition: FailureDisposition,
              changed_input: bool = False, evidence_refs: tuple[str, ...] = (),
              correlation: CorrelationRef | None = None, identity: FailureIdentity | None = None,
              escalation_available: bool = False):
        correlation = correlation or CorrelationRef()
        domain = RetryDomain(domain)
        with UnitOfWork(self.session_factory) as uow:
            task = self._task(uow, task_id, correlation)
            if task.state == TaskState.BLOCKED:
                raise ValueError("Resume through WorkflowEngine before scheduling retry")
            consumed = sum(e.event_type == "RETRY_SCHEDULED" and e.payload.get("domain") == domain.value
                           for e in uow.history.list_events(task_id))
            result = evaluate_retry(RetryRequest(domain=domain, disposition=disposition,
                current_attempt=consumed, changed_input=changed_input), self.config)
            if identity is not None:
                _, circuit = self._failure(uow, task_id, identity, correlation,
                    self._escalation_available(uow, task, escalation_available))
                if circuit.tripped:
                    result = type(result)(**{**result.model_dump(), "allowed": False,
                        "action": circuit.recommended_action, "reason_code": circuit.reason_code,
                        "reason": "Repeated normalized failure prohibits same-path retry."})
            kind = {RecoveryAction.BLOCK: DecisionType.BLOCK, RecoveryAction.FAIL: DecisionType.FAIL,
                    RecoveryAction.ESCALATE: DecisionType.ESCALATE_MODEL}.get(result.action, DecisionType.RETRY)
            event_type = "RETRY_SCHEDULED" if result.allowed else (
                "RETRY_EXHAUSTED" if result.reason_code == "RETRY_BUDGET_EXHAUSTED" else None)
            self._record(uow, task_id, kind, result.reason_code, result.reason,
                         evidence_refs, correlation, event_type, result.model_dump(mode="json"))
            uow.commit()
            return result

    def investigator_escalation(self, *, task_id: UUID, context: InvestigatorContext,
                                correlation: CorrelationRef | None = None):
        correlation = correlation or CorrelationRef()
        with UnitOfWork(self.session_factory) as uow:
            task = self._task(uow, task_id, correlation)
            if task.state != TaskState.INVESTIGATING:
                raise ValueError("Investigator escalation requires INVESTIGATING")
            count = sum(e.event_type == "MODEL_ESCALATED" for e in uow.history.list_events(task_id))
            # Durable counts and task cycle are authoritative; caller cannot reset the budget.
            context = InvestigatorContext(**{**context.model_dump(), "escalation_count": count,
                                             "defect_cycle": task.defect_cycle})
            result = evaluate_investigator_escalation(context, self.config)
            code = "ESCALATION_BUDGET_EXHAUSTED" if count >= self.config.investigator_escalation_limit else result.reason_codes[0]
            self._record(uow, task_id, DecisionType.ESCALATE_MODEL, code,
                "; ".join(result.reason_codes), result.evidence_refs, correlation,
                "MODEL_ESCALATED" if result.escalate else None, result.model_dump(mode="json"))
            uow.commit()
            return result

    def block(self, *, task_id: UUID, reason: BlockerReason, resume_state: TaskState,
              evidence_refs: tuple[str, ...] = (), correlation: CorrelationRef | None = None):
        correlation = correlation or CorrelationRef()
        result = evaluate_blocker(reason, resume_state, evidence_refs)
        with UnitOfWork(self.session_factory) as uow:
            self._task(uow, task_id, correlation)
            self._record(uow, task_id, DecisionType.BLOCK, result.reason_code, result.reason,
                         result.evidence_refs, correlation, "TASK_BLOCKED", result.model_dump(mode="json"))
            uow.commit()
            return result
