from enum import StrEnum

class TaskState(StrEnum):
    CREATED = "CREATED"
    RESEARCHING = "RESEARCHING"
    PLANNING = "PLANNING"
    IMPLEMENTING = "IMPLEMENTING"
    TESTING = "TESTING"
    ANALYZING = "ANALYZING"
    INVESTIGATING = "INVESTIGATING"
    REVIEWING = "REVIEWING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    DONE = "DONE"

class AgentName(StrEnum):
    RESEARCHER = "RESEARCHER"
    PLANNER = "PLANNER"
    IMPLEMENTER = "IMPLEMENTER"
    TEST_ANALYZER = "TEST_ANALYZER"
    INVESTIGATOR = "INVESTIGATOR"
    REVIEWER = "REVIEWER"

class ArtifactType(StrEnum):
    RESEARCH = "RESEARCH"
    PLAN = "PLAN"
    IMPLEMENTATION = "IMPLEMENTATION"
    TEST_RESULT = "TEST_RESULT"
    TEST_ANALYSIS = "TEST_ANALYSIS"
    INVESTIGATION = "INVESTIGATION"
    REVIEW = "REVIEW"

class GateResult(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"

class AgentInvocationStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"

class ErrorType(StrEnum):
    AGENT_ERROR = "AGENT_ERROR"
    SCHEMA_ERROR = "SCHEMA_ERROR"
    TOOL_ERROR = "TOOL_ERROR"
    TEST_FAILURE = "TEST_FAILURE"
    ENVIRONMENT_ERROR = "ENVIRONMENT_ERROR"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    WORKFLOW_ERROR = "WORKFLOW_ERROR"
    EXTERNAL_BLOCKER = "EXTERNAL_BLOCKER"

class ErrorSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class ErrorOwner(StrEnum):
    AGENT = "AGENT"
    TOOL = "TOOL"
    TEST_TARGET = "TEST_TARGET"
    ENVIRONMENT = "ENVIRONMENT"
    ORCHESTRATOR = "ORCHESTRATOR"
    EXTERNAL = "EXTERNAL"

class ReviewDecision(StrEnum):
    APPROVE = "APPROVE"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
    BLOCKED = "BLOCKED"

class InvestigationStatus(StrEnum):
    ROOT_CAUSE_IDENTIFIED = "ROOT_CAUSE_IDENTIFIED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ESCALATION_RECOMMENDED = "ESCALATION_RECOMMENDED"

class DecisionType(StrEnum):
    ROUTE_AGENT = "ROUTE_AGENT"
    RETRY = "RETRY"
    ESCALATE_MODEL = "ESCALATE_MODEL"
    TRANSITION = "TRANSITION"
    BLOCK = "BLOCK"
    FAIL = "FAIL"
    RESUME = "RESUME"

class PlannerDecision(StrEnum):
    READY_FOR_IMPLEMENTATION = "READY_FOR_IMPLEMENTATION"
    NEEDS_RESEARCH = "NEEDS_RESEARCH"
    BLOCKED = "BLOCKED"

class ImplementationStatus(StrEnum):
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"

class FailureClassification(StrEnum):
    LIKELY_PRODUCT_DEFECT = "LIKELY_PRODUCT_DEFECT"
    LIKELY_TEST_DEFECT = "LIKELY_TEST_DEFECT"
    LIKELY_ENVIRONMENT_ISSUE = "LIKELY_ENVIRONMENT_ISSUE"
    LIKELY_DATA_ISSUE = "LIKELY_DATA_ISSUE"
    UNKNOWN = "UNKNOWN"

class ReviewIssueSeverity(StrEnum):
    BLOCKER = "BLOCKER"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class TestExecutionStatus(StrEnum):
    COMPLETED = "COMPLETED"
    INCOMPLETE = "INCOMPLETE"
    FAILED = "FAILED"

class TestOutcome(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"

class ImplementationStepStatus(StrEnum):
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"

class ChangeType(StrEnum):
    CREATED = "CREATED"
    MODIFIED = "MODIFIED"
    DELETED = "DELETED"

class InvestigationActionType(StrEnum):
    CODE_FIX = "CODE_FIX"
    TEST_FIX = "TEST_FIX"
    MORE_RESEARCH = "MORE_RESEARCH"
    HUMAN_ACTION = "HUMAN_ACTION"

class CoverageStatus(StrEnum):
    COVERED = "COVERED"
    NOT_COVERED = "NOT_COVERED"
    UNVERIFIED = "UNVERIFIED"

class ActorType(StrEnum):
    ORCHESTRATOR = "ORCHESTRATOR"
    AGENT = "AGENT"
    TOOL = "TOOL"
    HUMAN = "HUMAN"
    SYSTEM = "SYSTEM"
