import type { CampaignView, CampaignRequirement, CampaignTestSpecification, CampaignTraceability, CampaignReadiness } from '../api/campaignTypes';
import { project, page } from './fixtures';
export const campaign: CampaignView = { id: 'campaign-a', project_id: project.id, name: 'Checkout QA', objective: 'Verify payment behavior', status: 'APPROVED', created_at: project.created_at, updated_at: project.updated_at };
export const requirement: CampaignRequirement = { id: 'requirement-a', project_id: project.id, campaign_id: campaign.id, extraction_id: 'extraction-a', key: 'PAY', logical_key: 'REQ-PAY', title: 'Accept payment', description: 'Accept a valid payment.',
  acceptance_criteria: [{ key: 'AC1', text: 'Payment is accepted.' }], source_references: [{ source_id: 'source-a', source_hash: 'a'.repeat(64), location_type: 'LINES', start_line: 2, end_line: 4, excerpt: 'Accept a valid payment.' }], information_markers: [], review_status: 'APPROVED', created_at: project.created_at, updated_at: project.updated_at };
export const blockedRequirement: CampaignRequirement = { ...requirement, id: 'requirement-b', key: 'CURRENCY', logical_key: 'REQ-CURRENCY', title: 'Accepted currency', review_status: 'NEEDS_CLARIFICATION', information_markers: [{ kind: 'AMBIGUITY', description: 'Clarify the supported currency.' }] };
export const specification: CampaignTestSpecification = { id: 'test-a', project_id: project.id, campaign_id: campaign.id, key: 'PAY', logical_key: 'TEST-PAY', title: 'Valid payment', test_type: 'FUNCTIONAL', priority: 'HIGH', preconditions: ['Valid account'],
  steps: [{ index: 1, action: 'Submit a payment', expected: 'Payment accepted' }], overall_expected_result: 'Payment accepted', required_evidence: ['Observed payment state'], information_markers: [], requirement_ids: [requirement.id], unresolved_requirement_refs: [],
  provenance: { origin: 'IMPORT', record_id: 'import-a', content_hash: 'b'.repeat(64), contract_version: 'test-import-v1', start_line: 2, end_line: 3 }, review_status: 'APPROVED', created_at: project.created_at, updated_at: project.updated_at };
export const blockedSpecification: CampaignTestSpecification = { ...specification, id: 'test-b', key: 'CURRENCY', logical_key: 'TEST-CURRENCY', title: 'Currency boundary', review_status: 'NEEDS_CLARIFICATION', requirement_ids: [], unresolved_requirement_refs: ['UNKNOWN-CURRENCY'], information_markers: [{ kind: 'UNRESOLVED_REQUIREMENT', description: 'Unknown Requirement reference.' }, { kind: 'MISSING_TRACEABILITY', description: 'No known Requirement links.' }], overall_expected_result: null };
export const traceability: CampaignTraceability = { project_id: project.id, campaign_id: campaign.id, requirements: page([
  { requirement_id: requirement.id, review_status: 'APPROVED', linked_test_count: 2, approved_test_count: 1, linked_test_review_states: { APPROVED: 1, READY_FOR_REVIEW: 1 }, coverage: 'COVERED' },
  { requirement_id: blockedRequirement.id, review_status: 'NEEDS_CLARIFICATION', linked_test_count: 1, approved_test_count: 0, linked_test_review_states: { READY_FOR_REVIEW: 1 }, coverage: 'PARTIAL' },
  { requirement_id: 'requirement-c', review_status: 'APPROVED', linked_test_count: 0, approved_test_count: 0, linked_test_review_states: {}, coverage: 'NOT_COVERED' },
]), links: page([{ requirement_id: requirement.id, test_spec_id: specification.id, test_review_status: 'APPROVED' }]) };
export const readiness: CampaignReadiness = { project_id: project.id, campaign_id: campaign.id, campaign_preparation_status: 'APPROVED', status: 'NOT_READY', total_requirements: 100, approved_requirements: 98, clarification_requirements: 2, total_test_specifications: 130, approved_test_specifications: 129,
  covered_requirements: 98, partial_requirements: 1, uncovered_requirements: 1, invalid_approved_requirements: 0, invalid_approved_test_specifications: 0, blocker_codes: ['REQUIREMENTS_NOT_APPROVED', 'REQUIREMENTS_NEED_CLARIFICATION', 'REQUIREMENT_COVERAGE_GAP'] };
